### PR TITLE
Add Ergodox "up one" layout to mapping

### PR DESCRIPTION
**Pull request by honza**
This moves all of the existing keys up by one key.  It eliminates the
use of the thumb cluster for increased comfort: some users find the
Ergodox thumb cluster awkward to use.

I'm not sure how to convince Keyboard Layout Editor to include the Miryoku graphic in the corner of the PNG. How do you generate these graphics?

### CODE REVIEW

**Comment by manna-harbour** [comment]
Thanks, I'll try it out! An extended thumbs option for this might also work.

**Comment by manna-harbour** [comment]
For the logos, the URLs in the decal key legends need updating. See https://github.com/manna-harbour/miryoku/blob/master/data/kmonad/miryoku-kle-kmonad.json for one that was recently updated. Also, the home keys need updating to match the shift.

**Comment by honza** [comment]
Logos fixed

**Comment by manna-harbour** [comment]
Thanks!

**Pull request closed without merging**
